### ISSUE TITLE
Change format of metadata.yml to move away from specifying git repos

### ISSUE THREAD

**Issue by ashb** [ministryofjustice/salt-shaker#16]
The new structure we came up with was:

```yaml
    dependencies:
     # Get any tagged version matching this specifier. Both the following 
     # forms are identical in behaviour.
     - ministryofjustice/sensu-formula: '>=1.1.2'
     - ministryofjustice/sensu-formula: { version: '>=1.1.2' }

     # This should get the latest *Release/tag*  of other-formula, not HEAD
     - ashb/other-formula

     # Does this get HEAD or the latest release tag? Again probably latest release 
     - ministryofjustice/logtstash-formula: { 
         git: 'https://github.com/ministryofjustice/logtstash-formula.git' 
       } 

     # You can specify a ref or a version with git repos too.
     - badger/foo-formula: { git: 'git@gitolite.local:foo', version: '>=v1.1.2' }
     - badger/foo-formula: { git: 'git@gitolite.local:foo', ref: 'master' }
```

(This is inspired by what you can put in a Gemfile.)
